engineer-man/felix

node/bot.js

Arrays start at 0, that's obvious - and now, the bot will tell the ones who believe the same that they are telling the truth, and it will tell the people who say arrays start at 1 that they are wrong.
TL;DR: Added a few message responses.

Teach the bot that arrays start at 0

---

python/cogs/responses.py

New gif command for the Python side

---

python/cogs/responses.py

Also, GIF names proven to be quite meaningless so they were removed

New commands

---

node/bot.js

updated the felix run usage message
to mention language selection by highlighting language

updated the felix run usage message

---

node/bot.js

You can flip a coin, open a book and tap a text with your eyes closed, you can ask friends or the cards or you use the Felix Oracle  :)

felix' coin toss added

---

python/cogs/graph.py

local var n error was accidentally added due to hasty implementation on my side. oops

fixed graph users + added message when number of people cut down

---

python/bot.py
python/cogs/chatlog.py
python/cogs/extra/aoc.py
python/cogs/extra/rc.py
python/cogs/extra/terminal.py
python/cogs/graph.py
python/cogs/helpall.py
python/cogs/jail.py
python/cogs/linkblocker.py
python/cogs/management.py
python/cogs/poll.py
python/cogs/purge.py
python/cogs/responses.py
python/cogs/stats.py

Made a few variables accessible from `client` in cogs by creating a custom class and removed a few unused imports.

Custom class for Felix

---

python/cogs/challenges.json
python/cogs/challenges.py

Added difficulty to the challenges command, which displays a random
challenge of a specific difficulty level.
There are some changes across the file to things such as spacing that were not made by me, but by being run through autopep8 so it complies with pep8.

Add difficulty selector to challenges command

---

python/bot.py
python/cogs/management.py
python/cogs/run.py

Also make use of `isinstance()` and `BadArgument()`.

Move error handling to management.py

---

python/cogs/general.py

Two new fields:
`Flagged` - Indicates if user is flagged or not
`Messages per day` - Shows the average message count per day

New fields for memberinfo command

---

python/cogs/management.py
python/cogs/superuser.py

An easier way to reload only the updated cogs.

Automatically reload updated cogs

---

python/cogs/jail.py

Informs team of unusual behavior in server and resolves #32 . These functions take no action besides informing the team once the threshold ir reached. This is because I don't know what actions the team would like to take, should be quite easy to implement with a list of `Member` objects.

Notify team when # users join threshold is reached

---

python/cogs/jail.py

I updated it a bit.
If you don't find anything wrong with it i will merge it into master.

Anti flood

---

.gitignore
python/cogs/general.py

- Added stackoverflow searching to `felix search`
- Fixed some indentation
- Added other options (he, she, they, we, @user) to `felix should i` command

Added felix search stackoverflow. Some python formatting fixes

---

python/cogs/linkblocker.py

Delete malicious and harmful files posted by members. For now only `.exe` files will be deleted and reported, reason being they've been causing most of the problems.

Delete malicious files

---

python/cogs/linkblocker.py

Further protection from malicious files

---

python/cogs/holidays.py

Should resolve #59 , the `set_holiday` method is quite long to implement activity reverting logic once a holiday or holidays end.

Holiday Activity Task

---

python/cogs/snippet.py

Sometimes people upload files without extensions, this allows us to specify a language to a user's uploaded file so that we can upload it. The downside of this syntax means that a user cannot specify the language of a file they are attaching to the same message as the `felix upload` command. I however think this is a fair compromise since in that use case they already have control over the extension.
This also addresses two minor issues that I felt were too small for their own PR, but will happily remove and place into separate PRs if desired:
- Use plaintext if no extension exists for the given file. Previously this would simply cause Felix to crash since it was doing an rsplit and blindly taking the second index.
- If the extension is not recognised, then give it plaintext extension …

Add manual language select to snippet

---

python/cogs/general.py

- add command that explains how are EM's weird stickers applied

Add felix howto sticker command

---

python/cogs/activities.py

Prevent sometimes incorrect bot status

Additional activity input processing

---

python/cogs/run.py
python/cogs/snippet.py

This method also allows to fetch a message from specific channels like so: `felix snippet channel_id-message_id`

Check if the provided message id exists

---

python/cogs/extra/chase.py

added a super awesome cog to load chase pics ^_^

---

python/cogs/extra/chase.py

Cog currently prints Picure #num instead of Picture #num

Fix typo in chase cog

---

python/cogs/jail.py

Not really an issue, but should resolve #85 and make felix look a bit smarter

Prevent felix from jailing itself

---

python/cogs/linkblocker.py

Relax forbidden link match slightly

Add boundaries to linkblocker regex

---

python/cogs/general.py

Adding the following new codes
```python
[
103, # EARLY_HINTS
418, # IM_A_TEAPOT
425
]
```

Adding httpcat missing codes

---

python/cogs/activities.py
python/cogs/hangman.py

Added some popular aussie holidays and fixed a typo..

add holidays and fixed typo

---

python/cogs/general.py

HTTP cats do not support all codes from HTTPStatus which caused empty embeds without an error message.
So I added all Http cats manually from their Github not the best solution but it works.

http cats status codes

---

python/cogs/general.py

found a newer api, fixed up embed look with chuck avatar.

changed api, fixed up embed look

---

python/cogs/general.py
python/cogs/jail.py

add rm novelty for jailing user, extended chuck to allow joke category to be selected by user, or a random one selected from all categories

add rm command and extended chuck

---

config.json.sample
python/cogs/general.py

ability to view NASA's Astronomy Picture of the Day, or view picture for a specified date in the past by `YYYY-MM-DD` format. (API key will need to be added to config.json)

NASAs Astronomy Picture of the Day

---

python/cogs/purge.py

method purger_user_time removes all messages from user in every channel within the last X seconds which defaults to 100

Added method purger_user_time

---

python/cogs/general.py

If wolfram couldn't understand the question, it tries searching using duckduck api. If api returns nothing, gives duckduckgo link

Reworked wolfram query

---

python/cogs/general.py

fix naive datetime error on calling memberinfo

fix naive dt error on update

---

python/cogs/general.py

Won't allow queries that would break duckduckgo api

duckcall exception handling

---

python/cogs/python_mailing_list.py

use dict copy to check and delete old mail hashes

use dict copy to check and delete old mail hashes

---

python/cogs/extra/aussie.py

add aussie extra cog for felix for australianisms to be used on australia day 26th Jan

aussie extra cog

---

Dockerfile
docker-compose.yml

bump python version to 3.10.2 and compose to v3

bump python version to 3.10.2 and compose to v3

---

python/cogs/general.py

collect a random nasa picture between start date and now

collect a random nasa picture between start date and now

---

python/cogs/spam_blocker.py

This PR will make Felix dump the spam list as a text file instead of flooding the channel it is run in.

Send spam list as file instead

---

.gitignore
python/cogs/spam_blocker.py

further fixes to spam ls dump, with ability to also dump the spam ls as a paginated code block - so it is easier to view on mobile devices.

Felix spam ls fix

---

python/cogs/aoc.py

Followed the previous formatting, I added it since my discord and AOC names were diffent.

Added my AOC id to known_users

---

python/cogs/spam_blocker.py

Now you can test a string against the entire spam list to see if your regex filter was written properly.

Add command to test string against spam list

---

python/cogs/general.py

Fixes the embed, so it should work as intended now.
It seems that public API is "deprecated", so it might stop working in the future entirely.

Fixes duckduckgo api request

---

python/cogs/general.py

Reverts engineer-man/felix#196

Revert "Update general.py"
